title: Anaji Kadam
logo: /assets/img/ak_headshot_circle.png
description: I'm Machine Learning Engineer at Pune, INDIA.<br><br><a href="mailto:anajikadam23@gmail.com">anajikadam23@gmail.com</a><br> <a href="https://in.linkedin.com/in/anaji-kadam-1944b2141/" target="_blank">View My LinkedIn Profile</a><br><a href="#" target="_blank">View Online Resume</a><br><a href="https://anajikadam.github.io/portfolio/" target="_blank">View Portfolio Projects</a>
show_downloads: false
theme: jekyll-theme-minimal
