title:      Mr. Anaji Kadam
logo: /assets/img/ak_headshot_circle.png
description: Machine Learning Engineer | Python <br><br><a href="mailto:anajikadam23@gmail.com">âœ‰ anajikadam23@gmail.com</a><br> <a href="https://in.linkedin.com/in/anaji-kadam-1944b2141/" target="_blank">ğŸ’¼ LinkedIn Profile</a><br><a href="#" target="_blank">ğŸ”— Online Resume</a><br><a href="#">ğŸ ï¸ Pune, MH, INDIA</a><br><a href="https://anajikadam.github.io/portfolio/" target="_blank">ğŸ“ Portfolio Projects</a>
show_downloads: false
theme: jekyll-theme-minimal
